version: '3.9'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - marketplace-network

  ms.cassandra.db:
    image: cassandra
    container_name: cassandra-container
    restart: always
    volumes: 
      - cassandra_data:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - marketplace-network

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - marketplace-network

  catalog.api:
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    container_name: catalog-api
    ports:
      - "5001:8080"
    depends_on:
      - rabbitmq
      - mongo
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__MongoDb: mongodb://mongo:27017
      MongoDbSettings__DatabaseName: CatalogDb
      RabbitMQ__Host: rabbitmq
    networks:
      - marketplace-network

  inventory.api:
    build:
      context: .
      dockerfile: Inventory.API/Dockerfile
    container_name: inventory-api
    ports:
      - "5002:8080"
    depends_on:
      - rabbitmq
      - mongo
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      RabbitMQ__Host: rabbitmq
      ConnectionStrings__MongoDb: mongodb://mongo:27017
      MongoDbSettings__DatabaseName: InventoryDb
    networks:
      - marketplace-network  # 🔥 ESTA LÍNEA ES LA QUE TE FALTABA

networks:
  marketplace-network:
    driver: bridge

volumes:
  mongo_data:
  rabbitmq_data: